name: AUR

on:
  push:
  schedule:
    - cron: "1 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
      - uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          tag: "aur"
          artifacts: "./dist/*.*"
          token: ${{ secrets.GITHUB_TOKEN }}
